### ISSUE TITLE
Модификаторы

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-CV#10]
Передавать в качестве параметра непосредственно имя класса не очень хорошая идея, если потом придется переименовать блок, то нужно будет искать по всему проекту, где передавались модификаторы, чтобы их тоже изменить. Лучше в миксине создать объект с ключами, которым будут соответствовать значения классов, и брать оттуда их названия (если же ключ отсутствует, то подставлять дефолтное значение). А в параметры передавать, например, просто "wide"

![Снимок экрана в 2019-08-20 22-47-14](https://user-images.githubusercontent.com/38564412/63379348-ce99a100-c39c-11e9-9041-884276200021.png)

**Comment by Feinminen** [comment]
Внёс правки.
