### ISSUE TITLE
Pug

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-CV#11]
Привести pug-файлы к единому стилю: 

убрать лишние пустые строки

![Снимок экрана в 2019-08-20 22-59-30](https://user-images.githubusercontent.com/38564412/63380000-37354d80-c39e-11e9-86a4-e6c46363913c.png)

после имен атрибутов не нужно ставить пробел:

![Снимок экрана в 2019-08-20 23-00-11](https://user-images.githubusercontent.com/38564412/63380034-503dfe80-c39e-11e9-95cd-742c8d27d17e.png)

Между фигурными скобками и содержимым где-то стоят пробелы, где-то нет, нужно везде сделать как здесь:

![Снимок экрана в 2019-08-20 23-01-45](https://user-images.githubusercontent.com/38564412/63380117-7ebbd980-c39e-11e9-9b27-7e9e923bdc28.png)

**Comment by Feinminen** [comment]
Внёс правки.
