### ISSUE TITLE
Общие вопросы

### ISSUE THREAD

**Issue by Sergio-Ka** [Feinminen/FSD-CV#16]
1. Не вижу смысла в навешенном display: flex на body. Так обычно не делается, создается обертка, на которую вешается подобное поведение. А главное просто лишний код, да еще и куча строчек пустых внизу. Оно конечно сжиматели всякие работают, но такой подход характеризует пишущего код не с лучшей стороны, неряшливо как-то выглядит.
2. Это лишнее так же console.log('Ready, Steady!'); Просто лишний код написанный не понятно для чего.

**Comment by Feinminen** [comment]
Внёс правки.
