### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-CV#3]
Имя блока, название файла sass, файла pug и миксина должны совпадать:

![Снимок экрана_2019-08-14_22-28-16](https://user-images.githubusercontent.com/38564412/63050099-f4c5c980-bee2-11e9-89ba-fbad8df121fe.png)

**Comment by MorganaLF** [comment]
В блоке не должно быть ничего лишнего, он не должен описывать другие блоки, например, в education присутствуют .education-wrapper, .mini-logo .mini-logo__title

![Снимок экрана_2019-08-14_22-30-13](https://user-images.githubusercontent.com/38564412/63050198-2e96d000-bee3-11e9-8503-777145ab711a.png)

**Comment by MorganaLF** [comment]
То же самое в pug - если у тебя миксин main-page, то внутри себя он может описывать только себя, другие блоки могут только инклюдиться. Я думаю, здесь и вовсе не блоки нужны, а элементы main-page

![Снимок экрана_2019-08-14_22-36-01](https://user-images.githubusercontent.com/38564412/63050522-02c81a00-bee4-11e9-9e8b-46c5195508f1.png)

**Comment by Feinminen** [comment]
Исправил.
P.S. Надеюсь всё правильно понял)

**Comment by MorganaLF** [comment]
Еще правки по БЭМ:
В соответствии с БЭМ, блоки не могут задавать внешнюю геометрию. Сейчас у тебя у некоторых блоков указаны margin.

**Comment by Feinminen** [comment]
Внёс правки.

**Comment by MorganaLF** [comment]
Ну марджин на паддинг заменить, если это по сути внешние отступы - не очень решение)
Если надо спозиционировать блок, задать ему отступы, то это делается через элемент-обертку родительского блока. 
Пункт 6: https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md

**Comment by Feinminen** [comment]
Внёс правки, перечитал бэст практис по БЭМ :)

**Comment by MorganaLF** [comment]
Здесь ты не совсем правильно понял. Отступы задаются в **родительском** блоке. То есть, например, создается элемент `.education__achieve-list,` в него кладется `+achieve-list`, и элементу `.education__achieve-list` задается маржин для `achieve-list`. 

В примере по ссылке выше как раз аналогичная ситуация.

**Comment by Feinminen** [comment]
Внёс правки.

**Comment by MorganaLF** [comment]
В `software-item` еще осталось

**Comment by Feinminen** [comment]
А в случае с sowtware-item не получится сделать обёртку у родителя, т.к. она обернёт сразу все блоки, а мне нужны отступы именно между самими блоками. Как в этом случае лучше сделать?
![отступы](https://user-images.githubusercontent.com/44312820/63448469-2c46ef80-c468-11e9-9ca8-bba4f7341590.png)

**Comment by MorganaLF** [comment]
Да, не обратила внимание, что у тебя цикл в ` software-item`. вообще обычно если называют item, то имеют ввиду один отдельный элемент, а не набор одинаковых элементов)

Я думаю, тут лучше переделать, чтобы в `software-item` содержался только один элемент, а цикл уже выводился в блоке `software`, так будет логичней.

**Comment by Feinminen** [comment]
Внёс правки.
