### ISSUE TITLE
Img

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-CV#4]
Навряд ли это просто див, сюда хотелось бы иметь возможность какое-то изображение поставить:

![Снимок экрана_2019-08-14_22-39-16](https://user-images.githubusercontent.com/38564412/63050748-736f3680-bee4-11e9-93ad-712ccb36c21b.png)

**Comment by Feinminen** [comment]
Исправил.

**Comment by MorganaLF** [comment]
Мне кажется, здесь тоже можно избавиться от if..else, задав классу background-color, а если есть изображение, то добавлять background-image. И кстати, откуда у дива альт-текст?)

**Comment by Feinminen** [comment]
Я исправил, но не логичнее ли было сделать в этом случае вот так?
Чтобы в случае с картинкой это был img с своим alt-ом, а если нет - то обычный див.
Насчёт alt текста - в какой-то из вариаций там был img)
![logoMixin](https://user-images.githubusercontent.com/44312820/63144750-84bc5e00-c01e-11e9-95ce-2a2ccaa0480d.png)

**Comment by MorganaLF** [comment]
Да, если не бэкграундом делать изображение, а тэгом, то лучше тогда последний вариант.

**Comment by Feinminen** [comment]
Исправил.

**Comment by Feinminen** [comment]
Исправил.
