### ISSUE TITLE
SASS

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-CV#5]
Не стоит повторять имя блока, нужно использовать &

![Снимок экрана_2019-08-14_22-42-41](https://user-images.githubusercontent.com/38564412/63050957-f2646f00-bee4-11e9-8866-d6976895c8af.png)

**Comment by MorganaLF** [comment]
Медиазапросы нужно помещать под блоками и элементами, к которым они относятся, а не в конце файла, это также позволит избежать дублирования и улучшит читаемость.

**Comment by Feinminen** [comment]
Исправил.

**Comment by MorganaLF** [comment]
Здесь еще немного привести все к единому стилю: элементы, псевдоэлементы, псевдоклассы, медиазапросы отбить пустой строкой, а вот в таких случаях пустые строки напротив не нужны

![Снимок экрана_2019-08-15_20-10-35](https://user-images.githubusercontent.com/38564412/63112393-cacede80-bf98-11e9-836a-03fdbe6be1a5.png)

**Comment by Feinminen** [comment]
Внёс правки.
