### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-CV#6]
Элемент блока по БЭМ это всегда имя существительное, поэтому элементы `.main-page__left` и `.main-page__right` названы некорректно:

![Снимок экрана_2019-08-15_19-35-19](https://user-images.githubusercontent.com/38564412/63110333-d8ce3080-bf93-11e9-8c08-4bf9ed50d05d.png)

Также необязательно для оберток использовать везде слова wrapper, container, это уместно, если, например, есть 

```
.main-page__logo-wrapper
    .main-page__logo
```

В твоем случае лучше просто назвать элемент `.main-page__logo`. Это нужно посмотреть по всему проекту.

**Comment by MorganaLF** [comment]
Для чего здесь в имени элемента уточняется, что это svg? Не стоит привязывать классы к тэгам, разметка может меняться, к тому же такие имена малоинформативны. Также нежелательно использовать сокращения (pic, exter).

![Снимок экрана_2019-08-15_19-38-13](https://user-images.githubusercontent.com/38564412/63110582-7590ce00-bf94-11e9-9332-5ab2c8ef363a.png)

**Comment by MorganaLF** [comment]
В проекте, по-моему, совсем не встречаются модификаторы. Вот это, например, явно напрашивается на модификаторы.

![Снимок экрана_2019-08-15_19-41-01](https://user-images.githubusercontent.com/38564412/63110670-acff7a80-bf94-11e9-8bbf-1e70df1bf052.png)

**Comment by MorganaLF** [comment]
Вот здесь тоже для заголовка пригодится модификатор, в инлайн-стилях тут нет никакой необходимости. 
Также тут можно убрать лишнее if..else и избавиться от дублирования. 
И еще заодно обрати внимание, что в БЭМ не приветствуются селекторы тэгов, а также использование тэгов без классов противоречит стандартам.

![Снимок экрана_2019-08-15_19-44-55](https://user-images.githubusercontent.com/38564412/63111028-6eb68b00-bf95-11e9-9910-3c38bd2fdc32.png)

**Comment by Feinminen** [comment]
Внёс правки.

**Comment by MorganaLF** [comment]
Для чего здесь используется строка, если можно написать `span.achieve-list__item-date= date`?

![Снимок экрана в 2019-08-19 10-40-23](https://user-images.githubusercontent.com/38564412/63247513-e3c3e200-c26d-11e9-8007-6e3e4ec63ef2.png)

**Comment by MorganaLF** [comment]
Есть ли здесь необходимость для каждой ячейки создавать свой класс? По идее ведь в одном столбце все ячейки должны быть одинаковые, значит, и класс у них должен быть один

![Снимок экрана в 2019-08-19 10-42-47](https://user-images.githubusercontent.com/38564412/63247676-4a490000-c26e-11e9-8822-e6150a69af33.png)

**Comment by Feinminen** [comment]
Внёс правки.

**Comment by MorganaLF** [comment]
По именам переменных: по их названиям не всегда понятно, что в них лежит. Из стандартов, это применимо и к pug:

> Имя переменной должно полно и точно описывать сущность и ее предназначение;

По имени переменной `modifiedClassTitle` ожидается, что там будет заголовок, а в ней лежит название модификатора. 

![Снимок экрана в 2019-08-19 18-30-27](https://user-images.githubusercontent.com/38564412/63278201-8a7ca280-c2af-11e9-90f5-dbe647cb6698.png)

`textTitle` - может, просто title?

![Снимок экрана в 2019-08-19 18-35-07](https://user-images.githubusercontent.com/38564412/63278553-26a6a980-c2b0-11e9-9081-b478e03fde3c.png)

В `skillPoint `лежит количество, о чем тоже из названия не ясно;

![Снимок экрана в 2019-08-19 18-36-53](https://user-images.githubusercontent.com/38564412/63278712-79806100-c2b0-11e9-8957-94b002890157.png)

Аналогично, в `barblue` неожиданно лежит ширина.

![Снимок экрана в 2019-08-19 18-38-50](https://user-images.githubusercontent.com/38564412/63279181-3e326200-c2b1-11e9-96a3-cb939d178b1b.png)


Вот здесь не обязательно к имени переменной добавлять название блока "logo", из контекста и так понятно, что речь о данном блоке. 

![Снимок экрана в 2019-08-19 18-33-50](https://user-images.githubusercontent.com/38564412/63278427-e810ef00-c2af-11e9-8119-5aea8948e15e.png)

**Comment by Feinminen** [comment]
Внёс правки.

**Comment by MorganaLF** [comment]
`barblueWidth` не очень хорошее название, во-первых, неверный порядок слов с т.зр. английского языка, во-вторых, голубая полоска всегда может стать какого-то другого цвета, нужно дать имя, соответствующее назначению, а не внешнему виду.

**Comment by Feinminen** [comment]
Внёс правки.
