### ISSUE TITLE
Инлайн-стили

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-CV#8]
Нужно стараться избегать инлайновых стилей, об этом есть в стандартах. Если в них нет непосредственной необходимости, то нужно описывать все через классы. 

![Снимок экрана в 2019-08-19 10-50-13](https://user-images.githubusercontent.com/38564412/63248037-2803b200-c26f-11e9-8b2a-d400d0d63681.png)

Например, вот здесь отступы и ширина линии ведь не динамически определяются, они известны заранее.

**Comment by Feinminen** [comment]
Привет. Там в макете в правой колонке у всех линий слега разные отступы, а в левой разная длина. Чтобы идеально подогнать под пиксель перфект приходилось у каждого из блоков менять эти параметры. Мне для каждого из блоков добавлять свой класс с другими отступами(e.g. mini-logo__line-experience) или просто не подгонять идеально?
![Расстояния](https://user-images.githubusercontent.com/44312820/63249016-c8b79900-c292-11e9-89d6-6b062666663c.png)

**Comment by MorganaLF** [comment]
Если, как в этом случае, это косяки макета, то стоит пренебречь пиксель перфектом. Здесь, думаю, очевидно, что это не задумка дизайнера, а на глаз нарисованные линии, так что горизонтальные отступы нужно сделать одинаковыми, и вертикально выровнять ровно по центру.

**Comment by Feinminen** [comment]
Внёс правки.
